import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';

const here = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(here, '.env');

function askSecret(prompt) {
  const input = process.stdin;
  process.stdout.write(prompt);

  return new Promise((resolve, reject) => {
    let value = '';
    const wasRaw = input.isRaw;

    const cleanup = () => {
      input.off('data', onData);
      input.setRawMode(wasRaw);
      input.pause();
      process.stdout.write('\n');
    };
    const onData = (chunk) => {
      for (const char of chunk.toString('utf8')) {
        if (char === '\u0003' || char === '\u0004') {
          cleanup();
          reject(new Error('Setup cancelled.'));
          return;
        }
        if (char === '\r' || char === '\n') {
          cleanup();
          resolve(value);
          return;
        }
        if (char === '\u007f' || char === '\b') {
          if (value.length) {
            value = [...value].slice(0, -1).join('');
            process.stdout.write('\b \b');
          }
          continue;
        }
        if (char >= ' ' && char !== '\u007f') {
          value += char;
          process.stdout.write('*');
        }
      }
    };

    input.setRawMode(true);
    input.resume();
    input.on('data', onData);
  });
}

function readEnvValue(contents, key) {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const line = contents
    .split(/\r?\n/)
    .find((entry) => new RegExp(`^\\s*(?:export\\s+)?${escapedKey}\\s*=`).test(entry));
  if (!line) return '';
  const raw = line.replace(/^\s*(?:export\s+)?[A-Za-z_][A-Za-z0-9_]*\s*=\s*/, '').trim();
  if (raw.startsWith('"')) {
    try {
      return JSON.parse(raw);
    } catch {}
  }
  if (raw.startsWith("'")) return raw.slice(1, raw.lastIndexOf("'"));
  return raw.replace(/\s+#.*$/, '').trim();
}

function mergeEnv(existing, updates) {
  if (!existing) {
    const lines = [
      '# Generated by npm run setup. Keep this file private.',
      ...Object.entries(updates).map(([key, value]) => `${key}=${JSON.stringify(value)}`),
      'PORT=3000',
    ];
    return lines.join('\n') + '\n';
  }

  const remaining = new Map(Object.entries(updates));
  const lines = existing.split(/\r?\n/).map((line) => {
    const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (!match || !remaining.has(match[1])) return line;
    const value = remaining.get(match[1]);
    remaining.delete(match[1]);
    return `${match[1]}=${JSON.stringify(value)}`;
  });
  for (const [key, value] of remaining) {
    lines.push(`${key}=${JSON.stringify(value)}`);
  }
  return lines.join('\n').replace(/\n*$/, '\n');
}

function saveEnv(contents, updating) {
  if (!updating) {
    let fd;
    let created = false;
    try {
      fd = fs.openSync(envPath, 'wx', 0o600);
      created = true;
      fs.writeFileSync(fd, contents, 'utf8');
      fs.fchmodSync(fd, 0o600);
      fs.closeSync(fd);
      return;
    } catch (error) {
      if (fd !== undefined) fs.closeSync(fd);
      if (created) {
        try {
          fs.unlinkSync(envPath);
        } catch {}
      }
      if (error.code === 'EEXIST') {
        throw new Error('.env was created by another process; setup left it unchanged.');
      }
      throw error;
    }
  }

  const temporaryPath = path.join(here, `.env.${process.pid}.tmp`);
  try {
    fs.writeFileSync(temporaryPath, contents, { encoding: 'utf8', flag: 'wx', mode: 0o600 });
    fs.chmodSync(temporaryPath, 0o600);
    fs.renameSync(temporaryPath, envPath);
    fs.chmodSync(envPath, 0o600);
  } catch (error) {
    try {
      fs.unlinkSync(temporaryPath);
    } catch {}
    throw error;
  }
}

async function main() {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error('Run setup in an interactive terminal, for example: npm run setup');
  }

  const updating = fs.existsSync(envPath);
  const existing = updating ? fs.readFileSync(envPath, 'utf8') : '';
  console.log('Covey setup');
  console.log('Use your Apple ID email and an app-specific password, not your normal Apple ID password.');
  console.log('Create an app-specific password at https://account.apple.com/');
  if (updating) {
    console.log('');
    console.log('An existing .env was found. Setup will update iCloud settings and preserve other entries.');
  }
  console.log('');

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  let email;
  let eventCalendar;
  let remindersCalendar;
  let dinnerCalendar;
  try {
    if (updating) {
      const confirm = (await rl.question('Continue and update the iCloud settings? [y/N]: ')).trim();
      if (!/^y(es)?$/i.test(confirm)) throw new Error('Setup cancelled.');
    }

    const savedEmail = readEnvValue(existing, 'ICLOUD_EMAIL');
    const emailAnswer = (await rl.question(`Apple ID email${savedEmail ? ` [${savedEmail}]` : ''}: `)).trim();
    email = emailAnswer || savedEmail;
    if (
      !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ||
      /^your|^placeholder/i.test(email) ||
      /@example\.(?:com|net|org)$/i.test(email)
    ) {
      throw new Error('Enter your actual Apple ID email address, not a placeholder.');
    }

    const savedCalendar = readEnvValue(existing, 'CALENDAR_NAME') || 'Family';
    const calendarAnswer = (await rl.question(`Existing iCloud calendar for events [${savedCalendar}]: `)).trim();
    eventCalendar = calendarAnswer || savedCalendar;
    remindersCalendar = (await rl.question('Optional reminders calendar name (leave blank to keep existing or skip): ')).trim();
    dinnerCalendar = (await rl.question('Optional dinner calendar name (leave blank to keep existing or skip): ')).trim();
  } finally {
    rl.close();
  }

  const password = (await askSecret('Apple app-specific password (input hidden): ')).replace(/\s/g, '');
  if (!password || /^(?:your|placeholder|change[_ -]?me|xxxx)/i.test(password)) {
    throw new Error('Enter your actual Apple app-specific password, not a placeholder.');
  }

  const updates = {
    ICLOUD_EMAIL: email,
    ICLOUD_APP_PASSWORD: password,
    CALENDAR_NAME: eventCalendar,
  };
  if (remindersCalendar) updates.REMINDERS_CALENDAR = remindersCalendar;
  if (dinnerCalendar) updates.DINNER_CALENDAR = dinnerCalendar;

  try {
    saveEnv(mergeEnv(existing, updates), updating);
  } catch (error) {
    throw new Error(`Could not write .env: ${error.message}`);
  }

  console.log('');
  console.log(`Setup ${updating ? 'updated' : 'complete'}. Credentials were saved to .env with owner-only permissions.`);
  console.log('Make sure the calendar names match calendars already present in iCloud.');
  console.log('Start Covey with: npm start');
}

main().catch((error) => {
  console.error(`\n${error.message}`);
  process.exitCode = 1;
});
